### PR TITLE
Apt proxy

### PR DESCRIPTION
**Pull request by tauhid621**
## Background

This PR adds proxy details to the `/etc/apt/apt.conf` file so that apt can work with proxies.

If not provided, `apt-get --assume-yes update` step fails with error `Unsupported proxy configured: ip://3128`

Screenshot 2024-09-05 at 4 50 21 PM

## How has this been tested?
Updated the module and deployed in azure with proxy. TFE was installed after this

### Did you add a new setting?

No

### CODE REVIEW

**Comment by kkavish** [comment]
@tauhid621 if I understand correctly, this is so that `apt-get` could work for VMs/containers deployed behind a proxy and thus don't have direct access to internet?

**Comment by tauhid621** [comment]
@kkavish Yes. `apt-get` for some reason is not working with the default proxy settings. One way to fix it is to use `/etc/apt/apt.conf` with proxy information

**Comment by kkavish** [comment]
LGTM!

**Review by kkavish — APPROVED** [review]

**Review by jkerry — APPROVED** [review]

**Comment by hamzahashicorp** [comment]
LGTM, but where is this final being templated? Is the proxy_ip being set anywhere, maybe in a tfvars file? I'm not seeing a default value being set other than the ones in the tpl files

**Comment by tauhid621** [comment]
@hamzahashicorp The files are being templated in the [main.tf](https://github.com/hashicorp/terraform-random-tfe-utility/blob/83848053578056c19a132df2335b126bb33b2ea8/modules/tfe_init/main.tf#L42) file of the module.
The [default](https://github.com/hashicorp/terraform-random-tfe-utility/blob/83848053578056c19a132df2335b126bb33b2ea8/modules/tfe_init/variables.tf#L103) values of proxy ip and port are null.

**Pull request merged**
