### PR TITLE
Migrated to tsccr-verified GH Action

### PR DESCRIPTION
**Pull request by NodyHub**
## Background

Migrate tflint GitHub action from forked version to official maintained version, which was already reviewed during a TSCCR security review.

## How has this been tested?
-/-

## This PR makes me feel
giphy

### CODE REVIEW

**Review by amy-hashi — APPROVED** [review]
LGTM

**Comment by anniehedgpeth** [comment]
@NodyHub do you know why it would be throwing 404 errors [here](https://github.com/hashicorp/terraform-random-tfe-utility/actions/runs/6222125486/job/16885440086?pr=117#step:3:7)?

**Comment by NodyHub** [comment]
Good question @anniehedgpeth, I will figure that out!

**Comment by NodyHub** [comment]
Looks like I mistakenly adjusted the tflint version to the general tag

**Comment by anniehedgpeth** [comment]
Thanks, @NodyHub !

**Pull request merged**
