### PR TITLE
RHEL 8.* support

### PR DESCRIPTION
**Pull request by jkerry**
## Background
This change adds support to the init scripts to support RHEL 8.* as a host vm platform.

## How has this been tested?
/test testing across all target clouds

### Did you add a new setting?
No

- [x] [AWS](https://github.com/hashicorp/terraform-aws-terraform-enterprise)
- [x] [Azure](https://github.com/hashicorp/terraform-azurerm-terraform-enterprise)
- [x] [GCP](https://github.com/hashicorp/terraform-google-terraform-enterprise)

### CODE REVIEW

**Comment by jkerry** [comment]
This change has passed all of the /test gates. The last reported failure shows as positive in the actual actions run so it's likely a bug in the reporting.

**Review by sandrampeter — APPROVED** [review]

**Pull request merged**
